### ISSUE TITLE
疑似存在rootkit后门，大家小心

### ISSUE THREAD

**Issue by kaliworld** [skisw/fastjson-exp#2]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/48043858/219945986-cbf41bba-1357-4d72-84a1-bbb1036e606d.png">

**Comment by amaz1ngday** [comment]
不知道你贴图是什么，反正我自己在用，功能就是发包，有的话直接反编译jar找代码贴出就行了，下载的大哥自己分辨吧。

**Comment by kaliworld** [comment]
> 

不好意思，我搞错了，我bp被投毒了，一开始以为是插件的问题，抱歉
